/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LambdaJavaShell;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testRunCmd() {
        App app = new App();
        assertEquals("test\n", app.runCmd("echo test"));
    }
}
